name: Firebase Upload

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  upload-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Or any other version you prefer

    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Install dependencies
      run: npm install firebase-admin

    - name: Set up Firebase Admin SDK credentials
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "${FIREBASE_SERVICE_ACCOUNT}" > "${HOME}/firebase-service-account.json"

    - name: Deploy to Firebase
      run: |
        node -e "
        var admin = require('firebase-admin');
        var serviceAccount = require('${HOME}/firebase-service-account.json');
        admin.initializeApp({
          credential: admin.credential.cert(serviceAccount)
        });
        console.log('success!');
        "
